Consider the below code to answer further questions:
* import numpy as np
* list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
* array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [2]:
import numpy as np

In [3]:
list_ = [ '1', '2', '3', '4', '5' ]
array_list = np.array(object = list_)

### Yes, there is a difference in the data types of the variables list_ and array_list.

list_ is a Python list, which can contain elements of different data types, including strings, integers, floats, etc. In this case, it contains string elements.

array_list is a NumPy array, all elements are strings, so the NumPy array's data type will be inferred as a string.

In [10]:
print("Data type of 'list_':", type(list_[0]))
print("Data type of 'array_list':", array_list.dtype)

Data type of 'list_': <class 'str'>
Data type of 'array_list': <U1


### dtype('<U1') represents a Unicode string data type with a fixed length of 1 character. 

Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.

In [13]:
print("Data types in 'list_':")
for i in list_:
    print(type(i))
    
print("\nData types in 'array_list':")    
for i in array_list:
    print(type(i))


Data types in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in 'array_list':
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

* array_list = np.array(object = list_, dtype = int)

* Will there be any difference in the data type of the elements present in both the variables, list_ and
array_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

### Yes, there will be a difference in the data types of the elements present in list_ and array_list after we specify the dtype as int during the creation of array_list.

In [17]:
print("Data types in 'list_':")
for i in list_:
    print(type(i))

print("\nData types in 'array_list':")
for i in array_list:
    print(type(i))

Data types in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in 'array_list':
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Consider the below code to answer further questions:
* import numpy as np
* num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
* num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) arr.shape
(ii) arr.size

In [19]:
import numpy as np

In [20]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [24]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
num_array.shape # shape: return's the shape of the Array

(2, 3)

In [27]:
num_array.size #size: returns number of elements present in the given array

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
* [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [34]:
array1 = np.zeros((3,3))
array1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
* [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])